CREATE TABLE `salesforce_contract_contract_data`
(
  `AccountID`                        int(12) NOT NULL,
  `ActivatedById`                    int(12) DEFAULT NULL,
  `ActivatedDate`                    datetime DEFAULT NULL,
  `BillingCity`                      varchar(40) DEFAULT NULL,
  `BillingCountry`                   varchar(80) DEFAULT NULL,
  `BillingCountryCode`               varchar(3) DEFAULT NULL,
  `BillingLatitude`                  float(19) DEFAULT NULL,
  `BillingLongitude`                 float(20) DEFAULT NULL,
  `BillingPostalCode`                varchar(20) DEFAULT NULL,
  `BillingState`                     varchar(80) DEFAULT NULL,
  `BillingStateCode`                 varchar(3) DEFAULT NULL,
  `BillingStreet`                    varchar(255) DEFAULT NULL,
  `BillToContactId`                  int(12) DEFAULT NULL,
  `CompanyAuthorizedById`            int(12) DEFAULT NULL,
  `CompanyAuthorizedDate`            date DEFAULT NULL,
  `ContractId`                       int(16) DEFAULT NULL,
  `CustomerAuthorizedById`           int(12) DEFAULT NULL,
  `CustomerAuthorizedDate`           date DEFAULT NULL,
  `Description`                      varchar(200) DEFAULT NULL,
  `EffectiveDate`                    date DEFAULT NULL,
  `EndDate`                          date DEFAULT NULL,
  `IsReductionOrder`                 tinyint(1) DEFAULT NULL,
  `LastReferencedDate`               datetime DEFAULT NULL,
  `LastViewedDate`                   datetime DEFAULT NULL,
  `Name`                             varchar(200) DEFAULT NULL,
  `OpportunityId`                    int(12) DEFAULT NULL,
  `OrderNumber`                      int(30) NOT NULL,
  `OrderReferenceNumber`             int(80) NOT NULL,
  `OriginalOrderId`                  int(12) DEFAULT NULL,
  `OwnerId`                          int(12) NOT NULL,
  `PoDate`                           date DEFAULT NULL,
  `PoNumber`                         int(80) DEFAULT NULL,
  `Pricebook2Id`                     varchar(40) NOT NULL,
  `QuoteId`                          int(12) DEFAULT NULL,
  `RecordTypeId`                     int(12) DEFAULT NULL,
  `ShippingCity`                     varchar(40) DEFAULT NULL,
  `ShippingCountry`                  varchar(80) DEFAULT NULL,
  `ShippingCountryCode`              varchar(3) DEFAULT NULL,
  `ShippingLatitude`                 float(19) DEFAULT NULL,
  `ShippingLongitude`                float(20) DEFAULT NULL,
  `ShippingPostalCode`               varchar(20) DEFAULT NULL,
  `ShippingState`                    varchar(80) DEFAULT NULL,
  `ShippingStateCode`                varchar(3) DEFAULT NULL,
  `ShippingStreet`                   varchar(255) DEFAULT NULL,
  `ShipToContactId`                  int(12) DEFAULT NULL,
  `Status`                           varchar(20) DEFAULT NULL,
  `StatusCode`                       varchar(20) DEFAULT NULL,
  `TotalAmount`                      float(13) DEFAULT NULL
  `Type`                             varchar(40) DEFAULT NULL,
  
    PRIMARY KEY (`OrderNumber`,`AccountID`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

